name: Test deployment from a PR

on: pull_request

env:
  DBT_PROFILE_TARGET:            test
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_TEST_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_TEST_PASSWORD }}
  DBT_PROFILE_ROLE:              CLOUD_COST_MONITORING_TEST_TRANSFORMER
  DBT_PROFILE_DB:                CLOUD_COST_MONITORING_TEST
  DBT_PROFILE_WH:                CLOUD_COST_MONITORING_TEST_WH

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt

    - name: Deploy
      run: |
        export DBT_PROFILE_SCHEMA=pr_$(date +%s)
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles
    